title: Your Name
description: Portfolio & Blog
baseurl: ""
url: "https://yourdomain.com"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

author:
  name: Your Name
  email: your.email@example.com

show_excerpts: true
